kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-node
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: juicefs-plugin
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --nodeid=$(NODE_NAME)
            - --v=1
            - --enable-manager=true
            - --config=/etc/config/config.yaml
          env:
            - name: KUBELET_PORT
              $patch: delete
            - name: HOST_IP
              $patch: delete
