apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# MUST be kube-system for pods with system-cluster-critical priorityClass
namespace: kube-system
patches:
- webhook.yaml
patchesJson6902:
- path: rbac.yaml
  target:
    group: rbac.authorization.k8s.io
    version: v1
    kind: ClusterRole
    name: juicefs-external-provisioner-role
resources:
- ../base
