apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# MUST be kube-system for pods with system-cluster-critical priorityClass
namespace: kube-system
resources:
- ../../../release
patches:
- path: daemonset.yaml
  target:
    kind: DaemonSet
- path: statefulset.yaml
  target:
    kind: StatefulSet
