apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# MUST be kube-system for pods with system-cluster-critical priorityClass
namespace: kube-system
resources:
- resources.yaml
commonLabels:
  app.kubernetes.io/name: juicefs-csi-driver
  app.kubernetes.io/instance: juicefs-csi-driver
  app.kubernetes.io/version: master
patches:
- container-resources.yaml
