kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: juicefs-plugin
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --nodeid=$(NODE_NAME)
            - --leader-election
            - --v=1
            - --webhook=true
            - --provisioner=true
            - --config=/etc/config/config.yaml
        - name: csi-provisioner
          $patch: delete
