kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: juicefs-plugin
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --nodeid=$(NODE_NAME)
            - --v=6
            - --webhook=true
            - --provisioner=true
        - name: csi-provisioner
          $patch: delete
---
$patch: delete
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-node
  namespace: kube-system
---
$patch: delete
kind: ServiceAccount
apiVersion: v1
metadata:
  name: juicefs-csi-node-sa
  namespace: kube-system
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: juicefs-csi-node-service-binding
---
$patch: delete
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: juicefs-csi-external-node-service-role
