kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: juicefs-plugin
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - mountPath: /jfs
              mountPropagation: Bidirectional
              name: jfs-dir
            - mountPath: /root/.juicefs
              mountPropagation: Bidirectional
              name: jfs-root-dir
            - mountPath: /etc/config
              name: juicefs-config
            - name: webhook-certs
              $patch: delete
      volumes:
        - name: webhook-certs
          $patch: delete
