apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
configurations:
- kustomizeconfig.yaml
resources:
- resources.yaml
secretGenerator:
- name: juicefs-secret
  envs:
  - secrets.env
