{{- if .Values.controller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "juicefs-csi.controllerLabels" . | nindent 4 }}
  name: {{ include "juicefs-csi.controllerFullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      {{- include "juicefs-csi.controllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "juicefs-csi.controllerSelectorLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --nodeid=$(NODE_ID)
        - --v=5
        env:
        - name: CSI_ENDPOINT
          value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
        image: "{{- include "juicefs-csi.controllerImage" . }}"
        imagePullPolicy: {{ .Values.controller.pullPolicy }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        name: juicefs-plugin
        resources:
          {{- toYaml .Values.controller.resources | nindent 12 }}
        ports:
        - containerPort: 9909
          name: healthz
          protocol: TCP
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --timeout=60s
        - --v=5
        env:
        - name: ADDRESS
          value: /var/lib/csi/sockets/pluginproxy/csi.sock
        image: "{{ .Values.controller.provisioner.registry }}/{{ .Values.controller.provisioner.repository }}:{{ .Values.controller.provisioner.tag }}"
        imagePullPolicy: {{ .Values.controller.provisioner.pullPolicy }}
        name: csi-provisioner
        resources:
          {{- toYaml .Values.controller.provisioner.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /var/lib/csi/sockets/pluginproxy/
          name: socket-dir
      - args:
        - --csi-address=$(ADDRESS)
        - --health-port=$(HEALTH_PORT)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: HEALTH_PORT
          value: "9909"
        name: liveness-probe
        image: "{{ .Values.controller.livenessComponent.registry }}/{{ .Values.controller.livenessComponent.repository }}:{{ .Values.controller.livenessComponent.tag }}"
        imagePullPolicy: {{ .Values.controller.livenessComponent.pullPolicy }}
        resources:
          {{- toYaml .Values.controller.livenessComponent.resources | nindent 12 }}
        volumeMounts:
        - mountPath: /csi
          name: socket-dir
      priorityClassName: system-cluster-critical
      serviceAccount: {{ include "juicefs-csi.serviceAccountName" . }}
      {{- with .Values.controller.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controller.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - emptyDir: {}
        name: socket-dir
{{- end }}
