{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "juicefs-csi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "juicefs-csi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "juicefs-csi.selectorLabels" . | nindent 4 }}
{{- end }}
