apiVersion: v1
kind: ConfigMap
metadata:
  name: juicefs-mount-config
  namespace: juicefs
data:
  # Default configuration for all StorageClasses
  default: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: DoesNotExist

  # StorageClass "juicefs-sc" configuration
  juicefs-sc: |
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: juicefs/mount-node
            operator: In
            values:
            - "true"
