kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: juicefs-csi-controller
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: juicefs-plugin
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --logtostderr
            - --nodeid=$(NODE_NAME)
            - --leader-election
            - --cache-client-conf
            - --v=6
