#!/bin/bash

# Copyright 2018 The Kubernetes Authors.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

${GOPATH}/bin/mockgen -package=mocks -destination=./pkg/driver/mocks/mock_mount.go k8s.io/utils/mount Interface
${GOPATH}/bin/mockgen -destination=./pkg/juicefs/mocks/mock_juicefs.go -package=mocks github.com/juicedata/juicefs-csi-driver/pkg/juicefs Interface
${GOPATH}/bin/mockgen -destination=./pkg/juicefs/mocks/mock_jfs.go -package=mocks github.com/juicedata/juicefs-csi-driver/pkg/juicefs Jfs
${GOPATH}/bin/mockgen -destination=./pkg/juicefs/mount/mocks/mock_mnt.go -package=mocks github.com/juicedata/juicefs-csi-driver/pkg/juicefs/mount MntInterface
