apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-pv
spec:
  csi:
    volumeAttributes:
      juicefs/mount-cpu-limit: 5000m
      juicefs/mount-memory-limit: 5Gi
      juicefs/mount-cpu-request: 1000m
      juicefs/mount-memory-request: 1Gi