apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

bases:
- ../../../deploy/kubernetes/base

secretGenerator:
- name: rsa-key
  files:
  - aaron.pem
  literals:
  - passphrase=testpass

patchesStrategicMerge:
- patches.yaml
