{{- if .Values.node.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/component: node
    {{- include "juicefs-csi.labels" . | nindent 4 }}
  name: juicefs-csi-node
  namespace: {{ .Release.Namespace | quote }}
spec:
  selector:
    matchLabels:
      app: juicefs-csi-node
      {{- include "juicefs-csi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: juicefs-csi-node
        {{- include "juicefs-csi.selectorLabels" . | nindent 8 }}
    spec:
    {{- if .Values.hostAliases }}
      hostAliases:
      {{- toYaml .Values.hostAliases | nindent 6 }}
    {{- end }}
      containers:
      - name: juicefs-plugin
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        {{- if .Values.image.pullPolicy }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- end }}
        args:
        - --endpoint=$(CSI_ENDPOINT)
        - --logtostderr
        - --nodeid=$(NODE_NAME)
        - --v=5
        - --enable-manager=true
        env:
        - name: CSI_ENDPOINT
          value: unix:/csi/csi.sock
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: JUICEFS_MOUNT_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: KUBELET_PORT
          value: "10250"
        - name: JUICEFS_MOUNT_PATH
          value: {{ .Values.jfsMountDir }}
        - name: JUICEFS_CONFIG_PATH
          value: {{ .Values.jfsConfigDir }}
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
        resources:
          {{- toYaml .Values.node.resources | nindent 10 }}
        ports:
        - containerPort: 9909
          name: healthz
          protocol: TCP
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: {{ .Values.kubeletDir }}
          mountPropagation: Bidirectional
          name: kubelet-dir
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /dev
          name: device-dir
        - mountPath: /jfs
          mountPropagation: Bidirectional
          name: jfs-dir
        - mountPath: /root/.juicefs
          mountPropagation: Bidirectional
          name: jfs-root-dir
      - name: node-driver-registrar
        image: {{ printf "%s:%s" .Values.sidecars.nodeDriverRegistrarImage.repository .Values.sidecars.nodeDriverRegistrarImage.tag }}
        args:
        - --csi-address=$(ADDRESS)
        - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
        - --v=5
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: DRIVER_REG_SOCK_PATH
          value: {{ .Values.kubeletDir }}/csi-plugins/csi.juicefs.com/csi.sock
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - rm -rf /registration/csi.juicefs.com-reg.sock /csi/csi.sock
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
        - mountPath: /registration
          name: registration-dir
      - name: liveness-probe
        image: {{ printf "%s:%s" .Values.sidecars.livenessProbeImage.repository .Values.sidecars.livenessProbeImage.tag }}
        args:
        - --csi-address=$(ADDRESS)
        - --health-port=$(HEALTH_PORT)
        env:
        - name: ADDRESS
          value: /csi/csi.sock
        - name: HEALTH_PORT
          value: "9909"
        volumeMounts:
        - mountPath: /csi
          name: plugin-dir
      {{- if .Values.node.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- with .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      {{- with .Values.node.affinity }}
      affinity:
        {{- tpl . $ | nindent 8 }}
      {{- end }}
      {{- with .Values.node.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.node.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccount: {{ include "juicefs-csi.node.serviceAccountName" . }}
      volumes:
      - hostPath:
          path: {{ .Values.kubeletDir }}
          type: Directory
        name: kubelet-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/csi-plugins/csi.juicefs.com/
          type: DirectoryOrCreate
        name: plugin-dir
      - hostPath:
          path: {{ .Values.kubeletDir }}/plugins_registry/
          type: Directory
        name: registration-dir
      - hostPath:
          path: /dev
          type: Directory
        name: device-dir
      - hostPath:
          path: {{ .Values.jfsMountDir }}
          type: DirectoryOrCreate
        name: jfs-dir
      - hostPath:
          path: {{ .Values.jfsConfigDir }}
          type: DirectoryOrCreate
        name: jfs-root-dir
{{- end }}
