{{ $namespace := .Release.Namespace | quote }}
{{- range $_, $sc := .Values.storageClasses }}

{{- if $sc.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $sc.name }}-secret
  namespace: {{ $namespace }}
  labels:
    {{- include "juicefs-csi.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- with $sc.backend }}
  name: {{ .name | b64enc | quote }}
  metaurl: {{ .metaurl | b64enc | quote }}
  {{- if .storage }}
  storage: {{ .storage | b64enc | quote }}
  {{- end }}
  {{- if .accessKey }}
  access-key: {{ .accessKey | b64enc | quote }}
  {{- end }}
  {{- if .secretKey }}
  secret-key: {{ .secretKey | b64enc | quote }}
  {{- end }}
  {{- if .bucket }}
  bucket: {{ .bucket | b64enc | quote }}
  {{- end }}
  {{- if .envs }}
  envs: {{ .envs | b64enc | quote }}
  {{- end }}
  {{- if .configs }}
  configs: {{ .configs | b64enc | quote }}
  {{- end }}
  {{- if .trashDays }}
  trash-days: {{ .trashDays | b64enc | quote }}
  {{- end }}
  {{- end }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  labels:
    {{- include "juicefs-csi.labels" $ | nindent 4 }}
  name: {{ $sc.name }}
{{- if $sc.mountOptions }}
mountOptions:
  {{- toYaml $sc.mountOptions | nindent 2 }}
{{- end }}
parameters:
  csi.storage.k8s.io/node-publish-secret-name: {{ $sc.name }}-secret
  csi.storage.k8s.io/node-publish-secret-namespace: {{ $namespace }}
  csi.storage.k8s.io/provisioner-secret-name: {{ $sc.name }}-secret
  csi.storage.k8s.io/provisioner-secret-namespace: {{ $namespace }}
  {{- with $sc.mountPod }}
  {{- if .resources.limits }}
  {{- if .resources.limits.cpu }}
  juicefs/mount-cpu-limit: {{ .resources.limits.cpu }}
  {{- end }}
  {{- if .resources.limits.memory }}
  juicefs/mount-memory-limit: {{ .resources.limits.memory }}
  {{- end }}
  {{- end }}
  {{- if .resources.requests }}
  {{- if .resources.requests.cpu }}
  juicefs/mount-cpu-request: {{ .resources.requests.cpu }}
  {{- end }}
  {{- if .resources.requests.memory }}
  juicefs/mount-memory-request: {{ .resources.requests.memory }}
  {{- end }}
  {{- end }}
  {{- end }}
provisioner: csi.juicefs.com
reclaimPolicy: {{ $sc.reclaimPolicy }}
volumeBindingMode: Immediate
{{- end }}
---

{{- end }}
