name: build csi slim image

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login Docker Hub
        env:
          PASSWORD: ${{ secrets.DOCKERHUB_FUSE_ACCESS_TOKEN }}
        run: docker login --username chnliyong --password ${PASSWORD}
      - name: Buildx and Push csi slim image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
          docker buildx create --use --name mybuilder
          make csi-slim-image-version
