name: Release Check For CE

on:
  workflow_dispatch:
  push:
    branches:
      - release_check

jobs:
  k8s-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare microk8s environment
        run: ${GITHUB_WORKSPACE}/.github/scripts/k8s-deps.sh
      - name: Login Docker Hub
        run: docker login --username chnliyong --password ${PASSWORD}
        env:
          PASSWORD: ${{ secrets.DOCKERHUB_FUSE_ACCESS_TOKEN }}
      - name: Build image
        env:
          DEV_K8S: microk8s
          JUICEFS_VERSION: release-1.0
        run: |
          cd ${GITHUB_WORKSPACE}
          make juicefs-image-release-check
          make image-release-check
          make image-release-check-push
      - name: webhook mode - Deploy JuiceFS CSI
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh webhook
      - name: webhook mode - Run ce test
        env:
          JUICEFS_STORAGE: s3
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: ce
          MOUNT_MODE: webhook
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-webhook.py
      - name: webhook provisioner mode - Deploy JuiceFS CSI
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh webhook-provisioner
      - name: webhook provisioner mode - Run ce test
        env:
          JUICEFS_STORAGE: s3
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: ce
          MOUNT_MODE: webhook
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-webhook-provisioner.py
      - name: pod mode - Deploy JuiceFS CSI for pod mode
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh pod
      - name: pod mode - Run ce test
        env:
          JUICEFS_STORAGE: "s3"
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: "ce"
          MOUNT_MODE: "pod"
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-pod.py
      - name: mount shared - Deploy JuiceFS CSI
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh pod-mount-share
      - name: mount shared - Run ce test
        env:
          JUICEFS_STORAGE: "s3"
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: "ce"
          MOUNT_MODE: "pod"
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-pod-share-mount.py
      - name: provisioner - Deploy JuiceFS CSI
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh pod-provisioner
      - name: provisioner - Run ce test
        env:
          JUICEFS_STORAGE: "s3"
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: "ce"
          MOUNT_MODE: "pod"
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-pod-provisioner.py
      - name: process mode - Deploy JuiceFS CSI
        run: |
          cd ${GITHUB_WORKSPACE}
          dev_tag=dev-$(git describe --always)
          echo "Dev tag is: " $dev_tag
          export dev_tag=$dev_tag
          .github/scripts/deploy-csi-in-k8s.sh process
      - name: process mode - Run ce test
        env:
          JUICEFS_STORAGE: "s3"
          JUICEFS_BUCKET: "http://juicefs-bucket.minio.default.svc.cluster.local:9000"
          JUICEFS_ACCESS_KEY: "minioadmin"
          JUICEFS_SECRET_KEY: "minioadmin"
          JUICEFS_NAME: "ce-secret"
          JUICEFS_META_URL: "redis://redis.default.svc.cluster.local:6379/1"
          JUICEFS_MODE: "ce"
          MOUNT_MODE: "process"
        run: |
          cd ${GITHUB_WORKSPACE}/.github/scripts/
          python3 ci-process.py
